name: "Daily Fudan"

on:
  schedule: # scheduled at (UTC+8) everyday
    - cron: "0 11 * * *"
    - cron: "0 23 * * *"
  workflow_dispatch:

env:
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: auto edit everyday
        run: python3 ./edit.py
      - name: push
        run: |
          git config user.name 'Github Actions'
          git config user.email 'github-actions@github.com'
          git add .
          git commit -m 'update by github actions'
          git push
      - name: Prepare daily fudan
        run: |
          git clone 'https://github.com/Ricardo-Evans/daily_fudan_core.git'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Daily fudan
        run: python3 ./daily_fudan_core/dailyFudan.py '${{ secrets.FUDAN }}'
